--caveat split issue with caveatname and json
authzed/zed pull request #191
Opened 2023-01-18 09:29 UTC by poklu

https://github.com/authzed/zed/issues/189

2023-01-18 09:31 UTC, poklu commented
I have read the CLA Document and I hereby sign the CLA

2023-01-18 10:40 UTC, vroldanbet reviewed
hi! thanks for submitting a PR! would you mind creating a test that reproduces the problem? 🙏🏻

2023-01-18 12:00 UTC, vroldanbet commented on internal/commands/relationship.go
> +				parts := strings.SplitN(caveatString, ":",2)
so what this solves is the scenario where your caveat value also includes a colon? Mind sharing your example?

2023-01-18 18:42 UTC, josephschorr approved these changes
(looks like lint broke)

2023-01-18 18:45 UTC, josephschorr requested changes

2023-02-16 20:04 UTC, josephschorr requested changes
LGTM

2023-02-16 20:04 UTC, josephschorr approved these changes

2023-02-16 20:04 UTC, merged