Filter improvements in zed
authzed/zed pull request #341
Opened 2024-02-07 20:38 UTC by josephschorr

Updates zed to support recently adding relationship filtering improvements in SpiceDB

Requires https://github.com/authzed/spicedb/pull/1739

2024-02-08 21:16 UTC, jzelinskie requested changes
two things on UX totally unrelated to your changes, but we should fix them up while we're here

2024-03-13 19:44 UTC, josephschorr commented on internal/commands/watch.go
> +
Can you link to this output?

2024-03-13 19:44 UTC, josephschorr commented on internal/commands/watch.go
> +	relFilters := make([]*v1.RelationshipFilter, 0, len(watchRelationshipFilters))
Changed to printf; can't use the real logger because this code is called in WASM

2024-03-14 16:12 UTC, josephschorr commented on internal/commands/watch.go
> +
Changed, but didn't add colors

2024-03-14 16:45 UTC, jzelinskie approved these changes

2024-03-14 16:47 UTC, jzelinskie approved these changes

2024-03-14 16:50 UTC, merged